server:
  port: 80

spring:
  application:
    name: cloud-order-service

eureka:
  client:
    #false 表示不向注册中心注册自己
    register-with-eureka: true
    #false 表示自己端就是注册中心，我的职责是维护服务实例，并不需要去检索服务
    fetchRegistry: true
    service-url:
#      defaultZone: http://localhost:7001/eureka #单机版
      defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka